name: Daily Stand Up Report Form
description: Guided DSU report form
title: "DSU Report YYYY-MM-DD - <last-name>"
labels: ["dsu"]
body: 
  - type: textarea
    id: finished
    attributes:
      label: Tasks Finished
      description: What tasks did you finish yesterday?
      placeholder: |
        1. issue-link:
        - <summary of accomplishment>
        2. https://github.com/issue-link-here: 
        - implemented tasks succesfully. Awaiting PR review
    validations:
      required: true
  - type: textarea
    id: in-progress
    attributes:
      label: Tasks In-progress
      description: What tasks are ongoing?
      placeholder: |
        1. <issue-link>: 
        - <summary of work done>
        2. https://github.com/issue-link-here: 
        - Partially implemented test.
    validations:
      required: true
  - type: textarea
    id: blockers
    attributes:
      label: Task Blockers
      description: What's preventing you from finishing the tasks?
      placeholder: |
        [ ] <issue-link>: <summary of issue>
        [ ] https://github.com/issue-link-here: Test requires missing features from developer team.
    validations:
      required: true
